"""username table added

Revision ID: 6e74cc897169
Revises: d8c8bcbc9f86
Create Date: 2024-07-12 17:47:40.278632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e74cc897169'
down_revision = 'd8c8bcbc9f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'username')
    # ### end Alembic commands ###
